services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    volumes:
      - "/workspaces/Building-Data-Warehouse/requirements/postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pgnetwork
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge



# docker run -it \
#   -e POSTGRES_USER="root" \
#   -e POSTGRES_PASSWORD="root" \
#   -e POSTGRES_DB="test_db" \
#   -v "c:/Users/LeebaThomas/repos/myrepos/deBC/data-eng-zoom/data-engineering-zoomcamp/week_1_basics_n_setup/2_docker_sql/postgres_data":/var/lib/postgresql/data \
#   -p 5432:5432 \
# --network=pg-network \
# --name pg-database \
#   postgres:13

# docker run -it \
#   -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
#   -e PGADMIN_DEFAULT_PASSWORD="root" \
#   -p   8080:80 \
#   --network=pg-network \
#   --name pgadmin \
#   dpage/pgadmin4
